### PR TITLE
Rewrote resolver for Tokio 0.1

### PR DESCRIPTION
**Pull request by partim**

### CODE REVIEW

**Comment by o01eg** [comment]
Any plans to release it?

**Comment by partim** [comment]
The code from this PR is part of the current series 0.2.

If you are referring to the new futures and async features, that should happen later this year.

**Comment by o01eg** [comment]
Oh, I got wrong PR. I thought it PR for migration from `tokio-core` to `tokio`. New `tokio` is based on stable `futures` 0.1.

**Comment by partim** [comment]
I’m still a bit torn on whether to wait or just do the rewrite already. Currently tending towards the latter. I just need to find the time …

**Pull request merged**
